# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "nine15-frontend"
client_id = "d8fe69b5bf00318029edf53483887150"
application_url = "https://symphony-calendar-lisa-wallet.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://symphony-calendar-lisa-wallet.trycloudflare.com/auth/callback",
  "https://symphony-calendar-lisa-wallet.trycloudflare.com/auth/shopify/callback",
  "https://symphony-calendar-lisa-wallet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pendo-production.myshopify.com"
